### ISSUE TITLE
Delete old migrations in a safe way for old and new deployments

### ISSUE THREAD

**Issue by aquabu** [CoMakery/comakery-server#1778]
# Goal

We have a lot of old migrations. If you were to `rake db:create` a database and then run `rake db:migrate` the migrations would fail because some of the methods used in migrations are no longer available. This can of course be avoided by running `rake db:prepare`. However, we should clean up the old migrations since they are no longer useful.

We also want to verify that the migrations run in the future and don't break by including a migration test during continuous integration (CI) which runs as a Github Action for the Repository. CI output is visible here: https://github.com/CoMakery/comakery-server/actions

We also want to be able to review the old migrations in the future even though we don't want to keep maintaining them. So we should tag the commit where they are removed.

## Requirements Checklist

A solution to this should satisfy the following requirements
- [ ] Add a tag to find an archive of old migrations `archive-migrations-to-[schema]`
- [x] remove the old migrations before June 1 2020
- [x] keep the migrations from the second half of 2020 since some of these may not have been run in all deployments
- [x] running `rake db:create` and `rake db:migrate` should migrate up to the current schema successfully without failures
- [ ] running migrations on existing staging, test and production environments should not cause problems with their schemas
- [ ] the GitHub workflow on CI should run all remaining migrations up and migrations down successfully as scripted in https://github.com/CoMakery/comakery-server/blob/acceptance/.github/workflows/test.yml

**Comment by ravi4rails** [comment]
@aquabu can you please confirm the second item in checklist?

**Comment by aquabu** [comment]
@ravi4rails yes, the idea is to shorten the number of migrations that will run. There may be some instances of CoMakery that need to run older migrations. All of the CoMakery instances we manage are up to date but there may be some versions deployed by other hosts that have a different version.

**Comment by ravi4rails** [comment]
@aquabu I pushed changes. And this worked using the reference you shared:
https://github.com/jalkoby/squasher
