### ISSUE TITLE
"Deploy To Heroku" button should deploy the whitelabel version of the app

### ISSUE THREAD

**Issue by aquabu** [CoMakery/comakery-server#1790]
# Goal

When the application is deployed to Heroku with the "Deploy To Heroku" button on the README it should use the whitelabel layout for the app similar to 

# Solution

- [x] app.json should have a default environment variable WHITELABEL=true
- [ ] when WHITELABEL=true then the app should use the whitelable layout
- [x] when WHITELABLE=true then the homepage should be the /projects page like https://whitelabel-audit.comakery.com/projects

**Comment by ravi4rails** [comment]
@aquabu I created an app on heroku using button click. The url is https://democomakery.herokuapp.com/

**Comment by ravi4rails** [comment]
However I just need to check whitelabel layout in app.
