### ISSUE TITLE
Re-enable transfer page charts and optimize their performace

### ISSUE THREAD

**Issue by aquabu** [CoMakery/comakery-server#1933]
The charts were disabled in this pull request for performance reasons https://github.com/CoMakery/comakery-server/pull/1917

This PR should be reverted and the charts should be optimized. The chart on `/projects/:id/dashboard/transfers page` looks like this:
<img width="1049" alt="Screen Shot 2021-03-16 at 12 54 17 AM" src="https://user-images.githubusercontent.com/7595/111274385-2be5ea80-85f2-11eb-97a5-9bb502807854.png">

A potential approach to optimizing the chart load time is:
* To reduce page response time, lazy load charts inside a turbo frame.
* Each time period (Day, Year, etc) for stacked chart should be only loaded when selected.

## Acceptance Criteria
* The charts are loaded
* The load time for the chart is minimal
* Confirm the filters work as expected including: Dates, Status, Account, Transfer History and Pagination

**Comment by Riddlerrr** [comment]
![image](https://user-images.githubusercontent.com/517356/111348749-8b470780-8691-11eb-900c-e91dc39046ba.png)

**Comment by aquabu** [comment]
Fixed in PR https://github.com/CoMakery/comakery-server/pull/1936
