### ISSUE TITLE
The Wallet API response should show wallet "name" and should not include the tokens array

### ISSUE THREAD

**Issue by aquabu** [CoMakery/comakery-server#1942]
## Acceptance Criteria

* Add `wallet.name` params into 
https://github.com/CoMakery/comakery-server/blob/6a7ad47040c52b6cf4b3fc4248f7df60df4c57b7/app/views/api/v1/wallets/_wallet.json.jbuilder#L2

* Remove unused `tokens` array from wallet API response 
https://github.com/CoMakery/comakery-server/blob/3e39bccd1ee14339e0e5025b6dc99b11eec2fadf/app/views/api/v1/wallets/_wallet.json.jbuilder#L12

* Update rspec tests
* Update the API documentation

**Comment by aquabu** [comment]
@Riddlerrr @Alexey1100 could you double check this is correct?

**Comment by Riddlerrr** [comment]
@aquabu 👍 Correct
