### ISSUE TITLE
bitcoinfees.earn.com API is giving bad data on fees

### ISSUE THREAD

**Issue by bretton** [CoMakery/comakery-server#2050]
Problem: `expect(axios.get).toHaveBeenCalledWith('https://bitcoinfees.earn.com/api/v1/fees/recommended')` is old data and incorrect fees for current market conditions on 20 April 2021.

Rather use `expect(axios.get).toHaveBeenCalledWith('https://mempool.space/api/v1/fees/recommended')` (from https://mempool.space/api)

**Comment by aquabu** [comment]
@bretton is this issue related to this repo? Thanks!

**Comment by bretton** [comment]
Hi, I did a search across github for projects using `https://bitcoinfees.earn.com/api/v1/fees/recommended`
I'm leaving a note to update to an alternative fees source as that one is publishing old & inaccurate data.

**Comment by aquabu** [comment]
ah - great! Thanks @bretton I appreciate it.
